language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get update
  - sudo apt-get install graphviz graphviz-dev
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - python -m pytest --cov=dot2bgraph
  - command -v dot2bgraph
  - dot2bgraph -h
after_success:
  - coveralls
